### ISSUE TITLE
[BUG] Documentation is inconsistent has multiple versions that lead to nothing working 

### ISSUE THREAD

**Issue by cryptofunallday** [wavesplatform/matcher#452]
Most of the comments here are revolving around the instructions failing to precisely outline what is needed to get matcher working.  How do I know?  Because I have gone through all of them including the various comments that someone keeps referring to when someone points out the documentation as their reference.  Why is this not documented correctly or properly?  Considering the age of this project and the potential it now has, logic, desire for success, and actual progress would clearly dictate the necessity for it, versus cherry picking comments to answer and then completely disregard.

I have tried the exact releases as mentioned, the git as mentioned and even laughed with the comment about the master branch not being what should be used against the matcher.  Why is the matcher not simply included in the source or the release and allowed to simply be enabled?  The appearance of multiple teams is how this seems and the multiple install methods leading to nothing is apparent as well.

What makes this worse is that none of the methods indicate anything about troubleshooting.  For example if you simply install the releases as the misleading documentation suggests you will find that the waves node daemon will start and without explanation it will not tell you why or you cannot reach the matcher API port.  Multiple issues have already been made about this and disregarded.  Why when it is obvious something is not right?

Can you tell any of us how to find out why the matcher API port is not activated yet the waves node daemon starts up?  I followed the multiple instructions for adding it to the node as an extension, the whole follow 6-7 in the README.MD does not work and this is proven by multiple people.

Can you provide a clear concise, actually working documented way to run the matcher or not?

**Comment by vsuharnikov** [comment]
> Can you tell any of us how to find out why the matcher API port is not activated yet the waves node daemon starts up?

Matcher is not a part of the NODE since 2.x. It is a separate service and uses NODE only to update balances and to send transactions. The Martcher Extension on NODE is required to do intercommunication things.

The documentation is actual for 2.2.4: https://github.com/wavesplatform/matcher/tree/v2.2.4 , but in the master tree it is a bit outdated. We're waiting for a checking of Docker images. After this the documentation will be simpler.

PS: Also note, Matcher don't share order books with other matchers in the network. It is a separate service. That's why it was removed from the NODE

**Comment by cryptofunallday** [comment]
As you are showing with this comment the documentation needs to be corrected.  A person looking to use this software would not calculate such a thing out of thin air.  Expecting them to do so is unrealistic.  What is the reason for not correcting the documentation to establish the proper installation?  Instead of various snippets such as these and in answer to others whom will continue to experience installation issues, it would seem wiser to be addressing issues AFTER the install.  Considering the age of this project, it would seem highly feasible if not necessary to ensure continued success.

In case you are not aware you should be to the fact that most people reading this will not be aware that there is no "NODE 2.x" on the releases page for "NODE" it is 1.2.17 as clearly shown here https://github.com/wavesplatform/Waves/releases further adding to the lack of proper documentation.  In addition as already established, pointed out, and currently provable there are multiple comments of multiple people trying different versions of the "Matcher 2.x" and the "NODE 1.x", none of the people who posted issues appears to have had any success.  Therefore you do not need to waste time writing pieces of the puzzle only adding to time wasting.  The documentation needs to be fixed, whether you want to accept this or not.

The documentation for the "Matcher v.2.2.4" branch you indicated does not work for the "NODE 1.2.17" release, considering how many have commented about attempting this it is surprising you are not accepting this fact, not aware, are disregarding it, or are ignoring that I mentioned multiple people reporting the same problem which indicates that you need to correct the documentation in its entirety.  Piecemeal answers that you keep giving are not solving the installation issues.  

Would you rather not focus on the issues after the installation instead of causing unnecessary forefront problems due to incorrect documentation or would you rather keep wasting time answering the same things over and over in pieces?

**Comment by viraladmin** [comment]
@cryptofunallday I am going to do what the kind developers in this repo are to kind to do. 

I won't reply to this after I make this comment, but you seem to like telling people how to do their job and trying to put people in check, so perhaps you will get the point if the rolls are reversed. 

First of all this is not Microsoft, not Sun Microsystems, not QuickBooks, nor is it any other closed source corporate piece of software in which you pay for something and as such have the right to expect it to work in a simple to use manner. This is free opensource software that you are free to use or not use as you wish. 

More importantly, this is a decentralized distributed project. If this project means so much to you that you would write such long posts complaining about the docs not being up to par - than one can assume you want to actually help the project succeed. I mean that's the only reason you would be setting up a matcher in the first place correct? You are not complaining because you are trying to clone it right? I will assume not. 

So since you are so drawn towards running your own matcher and own node, why not.... start documenting what does and doesn't work as you are building. There is actually a wiki link right in the main menu of the repo that you can clone and modify the documents of, then help recommend fixes and clarifications in the doc. Not only will you be helping the project, the coders might actually take an interest in who you are and what you are doing seeing as you are helping them. 

You also must be relatively new to how java works. Let me paste a quote directly from the oracle site about how versioning works with java. 

"Some of Oracle's products expose a version string which is separate from, but related to, the version number. This version string is usually only seen by programs which query the runtime environment, or by users who invoke command line tools. Version strings have the form 1.x, or 1.x.0, where x is the product version number.

In JDK 8 and JRE 8, the version strings are 1.8 and 1.8.0."

Thats right.... Java8 is actually.... version 1.8 or version 1.8.0 When you use command line tools.... you see that 1... but anywhere you look online will refer to it as java8 - not java 1.8. Welcome to the world of java. 

So when you see version 2.x in waves that means version 1.2.17 would be part of 2.x because the 1 is ignored. Its not up to waves team to educate you on the various languages and ways versioning works. 

If you are a developer you should know that docker is only an application management system. You are not bound to it. You can just as easily use the javac counterparts to compile and run the code or use any number of your own alternatives such as containerd, open vz, or LXC. Management tools are hardly "the lazy way" of doing things. If you don't know what you are talking about, best not speak. 

Again if you don't know the alternative commands - its not on waves team to teach you or to offer alternatives. Keep in mind despite you pointing out the few people on here that have asked questions, there are dozens of others, dare I say hundreds even, that have this successfully working. Its not nearly as bad as you are making it seem.

This final bit may actually help you in understanding all of this. First understand that waves is build using maven and github for management tools. With maven they use two repositories. I have no idea why they use two but I imagine the idea was originally to have a backup... obviously that doesn't work as they have some files in some repos and others in other repos. This could also relate to different levels of access within their teams. 

Second, the github side of things is becoming more popular but I must admit the waves team way of handling it is a bit unusual. In EVERYTHING relating to waves NOT JUST MATCHER it will help you to understand HOW waves operates with github. Waves uses the versioning history of github to define versions of their own applications, and they use the master branch as the "active in development" branch. Meaning if you want stable code that is guaranteed to work NEVER USE their master branches. Always look to see if they offer a precompiled set of the source first and if none exists look to the version tags and pick the latest. 

P.S The reason I assumed you are not just cloning this and are actually trying to build something to use WITHIN the waves ecosystem is because no one should ever complain that there are not enough docs to completely clone someone elses work. If you don't know enough to clone it, don't clone it as you won't know enough to modify it either.

**Comment by cryptofunallday** [comment]
Indeed I will document and contribute.  Thanks for your work and input.

**Comment by vsuharnikov** [comment]
Also we have a task to fresh our installation instructions for Matcher 2.3.*.  We'll update this soon.
